# Builds the SciAid mark from the Manrope ExtraBold "S" (SIL Open Font Licence):
#   src/ui/logoPath.js                     the glyph as an SVG path in a 100 x 100 box
#   assets/img/app-icon.png                1024 px, blue square with the white S
#   assets/img/adaptive-foreground.png     1024 px, white S inside the Android safe zone
#   assets/img/splash-logo.png             1024 px, rounded blue tile with the S
# Run from the repository root: python tools/brand/make_icons.py
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.boundsPen import BoundsPen
from PIL import Image, ImageDraw, ImageFont

BLUE = (3, 105, 161, 255)  # brand primary #0369a1
FONT = 'node_modules/@expo-google-fonts/manrope/800ExtraBold/Manrope_800ExtraBold.ttf'

font = TTFont(FONT)
glyphs = font.getGlyphSet()
glyph = glyphs[font.getBestCmap()[ord('S')]]
bounds = BoundsPen(glyphs)
glyph.draw(bounds)
x0, y0, x1, y1 = bounds.bounds

# The S fills 62% of the box height, centred, with the font's y axis flipped.
box, fill = 100, 0.62
scale = box * fill / (y1 - y0)
dx = box / 2 - (x0 + x1) / 2 * scale
dy = box / 2 + (y0 + y1) / 2 * scale
pen = SVGPathPen(glyphs, ntos=lambda v: ('%.2f' % v).rstrip('0').rstrip('.'))
glyph.draw(TransformPen(pen, (scale, 0, 0, -scale, dx, dy)))
with open('src/ui/logoPath.js', 'w', encoding='utf-8') as f:
    f.write('// The SciAid mark: the letter S from Manrope ExtraBold (SIL Open Font Licence),\n')
    f.write('// centred in a 100 x 100 box. Generated by tools/brand/make_icons.py.\n')
    f.write("export const LOGO_S = '%s';\n" % pen.getCommands())


def draw_s(img, size_px, centre, color=(255, 255, 255, 255)):
    """Draw the S so its cap height is size_px, centred on centre."""
    pil_font = ImageFont.truetype(FONT, 10)
    probe = pil_font.getbbox('S')
    target = int(10 * size_px / (probe[3] - probe[1]))
    pil_font = ImageFont.truetype(FONT, target)
    l, t, r, b = pil_font.getbbox('S')
    d = ImageDraw.Draw(img)
    d.text((centre[0] - (l + r) / 2, centre[1] - (t + b) / 2), 'S', font=pil_font, fill=color)


icon = Image.new('RGBA', (1024, 1024), BLUE)
draw_s(icon, 1024 * 0.62, (512, 512))
icon.save('assets/img/app-icon.png')

# Android crops adaptive icons to the inner 66%: keep the S well inside it.
fg = Image.new('RGBA', (1024, 1024), (0, 0, 0, 0))
draw_s(fg, 1024 * 0.40, (512, 512))
fg.save('assets/img/adaptive-foreground.png')

splash = Image.new('RGBA', (1024, 1024), (0, 0, 0, 0))
ImageDraw.Draw(splash).rounded_rectangle((112, 112, 912, 912), radius=180, fill=BLUE)
draw_s(splash, 800 * 0.62, (512, 512))
splash.save('assets/img/splash-logo.png')
print('done')
